import { Router, Request, Response } from 'express';
import { storage } from '../storage';
import { logSecurityEvent, SecurityEventType, LogSeverity } from '../security-logger';

const router = Router();

// Auth middleware
const isAuthenticated = async (req: Request, res: Response, next: Function) => {
  const authHeader = req.headers.authorization;
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.substring(7);
    try {
      const { verifyToken } = await import('../jwt');
      const decoded = verifyToken(token);
      if (decoded && decoded.userId) {
        req.session.userId = decoded.userId;
        return next();
      }
    } catch (error) {
      console.error('Token verification failed:', error);
    }
  }
  
  if (req.session && req.session.userId) {
    return next();
  }
  
  res.status(401).json({ error: 'Unauthorized' });
};

/**
 * GET /api/admin/security-report - Generate security report (admin only)
 */
router.get('/security-report', isAuthenticated, async (req: Request, res: Response) => {
  try {
    const userId = req.session.userId!;
    const user = await storage.getUser(userId);
    
    // Only users with USN starting with 'admin' can access
    if (!user || !user.usn.startsWith('admin')) {
      logSecurityEvent(
        SecurityEventType.ACCESS_DENIED,
        LogSeverity.WARNING,
        req,
        `Unauthorized access attempt to security report by user ${user?.usn || 'unknown'}`
      );
      return res.status(403).json({ error: 'You do not have permission to access this resource' });
    }
    
    const { generateSecurityReport } = await import('../security-report');
    const report = generateSecurityReport();
    
    console.log(`Security report generated by admin user ${user.usn}`);
    
    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', 'attachment; filename="security-report.md"');
    res.send(report);
  } catch (error) {
    console.error('Error generating security report:', error);
    res.status(500).json({ error: 'Failed to generate security report' });
  }
});

export default router;
